using System.Text.RegularExpressions;
using Bogus;
using DtPipe.Core.Abstractions;
using DtPipe.Core.Models;
using DtPipe.Core.Options;

using Apache.Arrow;
using Apache.Arrow.Types;

namespace DtPipe.Transformers.Hybrid.Fake;

/// <summary>
/// Transforms data rows by replacing specified columns with fake data generated by Bogus.
/// Supports column references using {COLUMN_NAME} syntax for composing values.
/// </summary>
public sealed partial class FakeDataTransformer : IColumnarTransformer, IRequiresOptions<DtPipe.Transformers.Hybrid.Fake.FakeOptions>
{
	private List<DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor>? _processors;
	private readonly DtPipe.Transformers.Hybrid.Fake.FakerRegistry _fakerRegistry;
	private readonly DtPipe.Transformers.Hybrid.Fake.FakeMappingParser _mappingParser;
	private readonly DtPipe.Transformers.Hybrid.Fake.FakeOptions _options;
	private readonly string _locale;
	private readonly Faker _faker;

	// Deterministic mode fields
	private readonly string? _seedColumn;
	private readonly bool _deterministic;
	private readonly bool _skipNull;
	private int _seedColumnIndex = -1;
	private long _rowCounter = 0;

	// Paged caches for deterministic mode
	private Dictionary<int, DtPipe.Transformers.Hybrid.Fake.PagedFakeValueCache>? _pagedCaches;

	// State initialized in InitializeAsync
	private int[]? _generationOrder;
	private Dictionary<string, int>? _columnNameToIndex;
	private readonly List<string> _virtualColumns = [];
	private int _realColumnCount;
	private Schema? _outputSchema;

	// Regex for template substitution
	[GeneratedRegex(@"\{([^{}]+)\}", RegexOptions.Compiled)]
	private static partial Regex TemplatePattern();

	public FakeDataTransformer(DtPipe.Transformers.Hybrid.Fake.FakeOptions options)
	{
		_options = options;
		_fakerRegistry = new DtPipe.Transformers.Hybrid.Fake.FakerRegistry();
		_mappingParser = new DtPipe.Transformers.Hybrid.Fake.FakeMappingParser(_fakerRegistry);
		_locale = options.Locale;
		_seedColumn = options.SeedColumn;
		_deterministic = options.Deterministic;
		_skipNull = options.SkipNull;

		_faker = options.Seed.HasValue
			? new Faker(options.Locale) { Random = new Randomizer(options.Seed.Value) }
			: new Faker(options.Locale);

		if (_deterministic && !string.IsNullOrEmpty(_seedColumn))
		{
			throw new ArgumentException("Options --fake-deterministic and --fake-seedcolumn cannot be used together.");
		}

		_mappingParser.ParseAll(options.Fake);
	}

	public bool HasFake => _mappingParser.HasMappings;
	public DtPipe.Transformers.Hybrid.Fake.FakerRegistry Registry => _fakerRegistry;

	public ValueTask<IReadOnlyList<PipeColumnInfo>> InitializeAsync(IReadOnlyList<PipeColumnInfo> columns, CancellationToken ct = default)
	{
		if (!HasFake)
		{
			_processors = null;
			_generationOrder = null;
			return new ValueTask<IReadOnlyList<PipeColumnInfo>>(columns);
		}

		// Build column name to index map
		_columnNameToIndex = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
		_realColumnCount = columns.Count;
		for (var i = 0; i < columns.Count; i++)
		{
			_columnNameToIndex[columns[i].Name] = i;
		}

		// Detect virtual columns
		_virtualColumns.Clear();
		foreach (var colName in _mappingParser.Mappings.Keys)
		{
			if (!_columnNameToIndex.ContainsKey(colName))
			{
				var virtualIndex = _realColumnCount + _virtualColumns.Count;
				_columnNameToIndex[colName] = virtualIndex;
				_virtualColumns.Add(colName);
			}
		}

		var totalColumns = _realColumnCount + _virtualColumns.Count;

		// Build processors
		var processors = new DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor[totalColumns];
		var templateColumns = new List<int>();
		var nonTemplateColumns = new List<int>();

		// Process real columns
		for (var i = 0; i < columns.Count; i++)
		{
			var colName = columns[i].Name;
			if (!_mappingParser.Mappings.TryGetValue(colName, out var value))
			{
				continue;
			}

			if (DtPipe.Transformers.Hybrid.Fake.FakeMappingParser.IsTemplate(value))
			{
				var refCols = DtPipe.Transformers.Hybrid.Fake.FakeMappingParser.ExtractReferencedColumns(value);
				processors[i] = new DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor(i, value, refCols);
				templateColumns.Add(i);
			}
			else
			{
				var generator = BuildGenerator(value, colName);
				processors[i] = new DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor(i, generator, value);
				nonTemplateColumns.Add(i);
			}
		}

		// Process virtual columns
		foreach (var virtualCol in _virtualColumns)
		{
			var virtualIndex = _columnNameToIndex[virtualCol];
			var value = _mappingParser.Mappings[virtualCol];

			if (DtPipe.Transformers.Hybrid.Fake.FakeMappingParser.IsTemplate(value))
			{
				var refCols = DtPipe.Transformers.Hybrid.Fake.FakeMappingParser.ExtractReferencedColumns(value);
				processors[virtualIndex] = new DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor(virtualIndex, value, refCols);
				templateColumns.Add(virtualIndex);
			}
			else
			{
				var generator = BuildGenerator(value, virtualCol);
				processors[virtualIndex] = new DtPipe.Transformers.Hybrid.Fake.FakeColumnProcessor(virtualIndex, generator, value);
				nonTemplateColumns.Add(virtualIndex);
			}
		}

		_processors = processors.ToList();
		_generationOrder = [.. nonTemplateColumns, .. templateColumns];

		// Resolve seed column index
		if (_seedColumn is not null && !_columnNameToIndex.TryGetValue(_seedColumn, out _seedColumnIndex))
		{
			throw new InvalidOperationException($"Seed column '{_seedColumn}' not found in result set.");
		}

		// Initialize deterministic caches
		if (_deterministic || _seedColumnIndex >= 0)
		{
			_pagedCaches = [];
			foreach (var idx in _generationOrder)
			{
				var proc = _processors[idx];
				if (proc.Generator is not null)
				{
					_pagedCaches[idx] = new DtPipe.Transformers.Hybrid.Fake.PagedFakeValueCache(_locale, proc.Generator, proc.FakerHash);
				}
			}
		}

		// Prepare output columns schema
		var outputColumns = new List<PipeColumnInfo>(columns);
		foreach (var virtualColName in _virtualColumns)
		{
			var fakerPath = _mappingParser.Mappings[virtualColName];
			Type colType = typeof(string);

			// Try to infer type from registry
			if (!DtPipe.Transformers.Hybrid.Fake.FakeMappingParser.IsTemplate(fakerPath))
			{
				var hashIndex = fakerPath.IndexOf('#');
				var basePath = hashIndex >= 0 ? fakerPath[..hashIndex] : fakerPath;
				colType = _fakerRegistry.GetReturnType(basePath) ?? typeof(string);
			}

			outputColumns.Add(new PipeColumnInfo(virtualColName, colType, true));
		}

		_outputSchema = BuildArrowSchema(outputColumns);
		return new ValueTask<IReadOnlyList<PipeColumnInfo>>(outputColumns);
	}

	private Schema BuildArrowSchema(IReadOnlyList<PipeColumnInfo> columns)
	{
		var builder = new Schema.Builder();
		foreach (var col in columns)
		{
			builder.Field(new Field(col.Name, GetArrowType(col.ClrType), true));
		}
		return builder.Build();
	}

	private IArrowType GetArrowType(Type type)
	{
		var baseType = Nullable.GetUnderlyingType(type) ?? type;
		if (baseType == typeof(string)) return StringType.Default;
		if (baseType == typeof(bool)) return BooleanType.Default;
		if (baseType == typeof(int)) return Int32Type.Default;
		if (baseType == typeof(long)) return Int64Type.Default;
		if (baseType == typeof(double)) return DoubleType.Default;
		if (baseType == typeof(float)) return FloatType.Default;
		if (baseType == typeof(DateTime)) return Date64Type.Default;
		if (baseType == typeof(DateTimeOffset)) return TimestampType.Default;
		return StringType.Default;
	}

	private Func<Faker, object?> BuildGenerator(string fakerPath, string colName)
	{
		var hashIndex = fakerPath.IndexOf('#');
		var basePath = hashIndex >= 0 ? fakerPath[..hashIndex] : fakerPath;

		var generator = _fakerRegistry.GetGenerator(basePath);
		if (generator is not null) return generator;

		// Fallback: treat as hardcoded string
		return _ => fakerPath;
	}

	public object?[]? Transform(object?[] row)
	{
		_rowCounter++;

		if (_processors is null || _generationOrder is null) return row;

		var totalColumns = _realColumnCount + _virtualColumns.Count;
		var resultRow = new object?[totalColumns];
		System.Array.Copy(row, resultRow, _realColumnCount);

		// Initialize virtual columns with null for safety
		for (int i = 0; i < _virtualColumns.Count; i++)
		{
			resultRow[_realColumnCount + i] = null;
		}

		// Row-level seed for deterministic mode
		int? rowSeed = null;
		if (_deterministic)
		{
			rowSeed = (int)(_rowCounter & 0x7FFFFFFF);
		}
		else if (_seedColumnIndex >= 0)
		{
			var seedVal = resultRow[_seedColumnIndex];
			if (seedVal is not null)
			{
				rowSeed = (int)(DtPipe.Transformers.Hybrid.Fake.StableHash.Compute(seedVal) & 0x7FFFFFFF);
			}
		}

		foreach (var idx in _generationOrder)
		{
			// Skip if source is null and SkipNull is enabled (for real columns only)
			if (_skipNull && idx < _realColumnCount && resultRow[idx] is null)
			{
				continue;
			}

			var proc = _processors[idx];
			if (proc.IsTemplate)
			{
				resultRow[idx] = ProcessTemplate(resultRow, proc.Template!, proc.ReferencedColumns!);
			}
			else if (proc.Generator is not null)
			{
				if (rowSeed.HasValue && _pagedCaches!.TryGetValue(idx, out var cache))
				{
					// Use paged cache for deterministic/seedcolumn mode
					resultRow[idx] = cache.GetValue(rowSeed.Value);
				}
				else
				{
					// Normal random mode
					resultRow[idx] = proc.Generator(_faker);
				}
			}
		}

		return resultRow;
	}

	private object? ProcessTemplate(object?[] row, string template, HashSet<string> refCols)
	{
		return TemplatePattern().Replace(template, match =>
		{
			var colName = match.Groups[1].Value;
			if (_columnNameToIndex!.TryGetValue(colName, out var idx))
			{
				return row[idx]?.ToString() ?? "";
			}
			return match.Value;
		});
	}

	public ValueTask<RecordBatch?> TransformBatchAsync(RecordBatch batch, CancellationToken ct = default)
	{
		if (_processors is null || _generationOrder is null || _outputSchema is null)
			return new ValueTask<RecordBatch?>(batch);

		int rowCount = batch.Length;
		int totalColumns = _processors.Count;
		var builders = CreateBuilders(_outputSchema, rowCount);

		// Row buffer for Bogus and Templates
		var rowBuffer = new object?[totalColumns];

		// Appenders for efficient batching (reusing bridge logic or similar)
		// To simplify, we'll use a direct loop.

		for (int i = 0; i < rowCount; i++)
		{
			_rowCounter++;

			// 1. Extract real columns from incoming batch into rowBuffer
			for (int colIdx = 0; colIdx < _realColumnCount; colIdx++)
			{
				rowBuffer[colIdx] = GetValueFromArrow(batch.Column(colIdx), i);
			}
			// Initialize virtual columns if any
			for (int colIdx = _realColumnCount; colIdx < totalColumns; colIdx++)
			{
				rowBuffer[colIdx] = null;
			}

			// 2. Deterministic Row Seed
			int? rowSeed = null;
			if (_deterministic)
			{
				rowSeed = (int)(_rowCounter & 0x7FFFFFFF);
			}
			else if (_seedColumnIndex >= 0)
			{
				var seedVal = rowBuffer[_seedColumnIndex];
				if (seedVal is not null)
				{
					rowSeed = (int)(DtPipe.Transformers.Hybrid.Fake.StableHash.Compute(seedVal) & 0x7FFFFFFF);
				}
			}

			// 3. Process Generation Order
			foreach (var idx in _generationOrder)
			{
				if (_skipNull && idx < _realColumnCount && rowBuffer[idx] is null)
				{
					continue;
				}

				var proc = _processors[idx];
				if (proc.IsTemplate)
				{
					rowBuffer[idx] = ProcessTemplate(rowBuffer, proc.Template!, proc.ReferencedColumns!);
				}
				else if (proc.Generator is not null)
				{
					if (rowSeed.HasValue && _pagedCaches!.TryGetValue(idx, out var cache))
					{
						rowBuffer[idx] = cache.GetValue(rowSeed.Value);
					}
					else
					{
						rowBuffer[idx] = proc.Generator(_faker);
					}
				}
			}

			// 4. Append row to builders
			for (int colIdx = 0; colIdx < totalColumns; colIdx++)
			{
				AppendValueToBuilder(builders[colIdx], rowBuffer[colIdx]);
			}
		}

		// 5. Build final result batch
		var resultArrays = builders.Select(b => BuildArray(b)).ToList();
		return new ValueTask<RecordBatch?>(new RecordBatch(_outputSchema, resultArrays, rowCount));
	}

	private static object? GetValueFromArrow(IArrowArray array, int index)
	{
		if (array.IsNull(index)) return null;

		return array switch {
			StringArray a => a.GetString(index),
			Int32Array a => a.GetValue(index),
			Int64Array a => a.GetValue(index),
			DoubleArray a => a.GetValue(index),
			FloatArray a => a.GetValue(index),
			BooleanArray a => a.GetValue(index),
			Date64Array a => a.GetDateTime(index),
			TimestampArray a => a.GetTimestamp(index),
			_ => null
		};
	}

	private static IArrowArrayBuilder[] CreateBuilders(Schema schema, int capacity)
	{
		return schema.FieldsList.Select(f => CreateBuilder(f.DataType)).ToArray();
	}

	private static IArrowArrayBuilder CreateBuilder(IArrowType type)
	{
		return type.TypeId switch
		{
			ArrowTypeId.Boolean => new BooleanArray.Builder(),
			ArrowTypeId.Int32 => new Int32Array.Builder(),
			ArrowTypeId.Int64 => new Int64Array.Builder(),
			ArrowTypeId.Double => new DoubleArray.Builder(),
			ArrowTypeId.Float => new FloatArray.Builder(),
			ArrowTypeId.String => new StringArray.Builder(),
			ArrowTypeId.Timestamp => new TimestampArray.Builder(),
			ArrowTypeId.Date64 => new Date64Array.Builder(),
			_ => new StringArray.Builder()
		};
	}

	private static void AppendValueToBuilder(IArrowArrayBuilder builder, object? value)
	{
		if (value == null) { AppendNull(builder); return; }

		if (builder is StringArray.Builder s) s.Append(value.ToString() ?? "");
		else if (builder is Int32Array.Builder i32 && value is int iv) i32.Append(iv);
		else if (builder is Int64Array.Builder i64 && value is long lv) i64.Append(lv);
		else if (builder is DoubleArray.Builder dbl && value is double dv) dbl.Append(dv);
		else if (builder is FloatArray.Builder flt && value is float fv) flt.Append(fv);
		else if (builder is BooleanArray.Builder b && value is bool bv) b.Append(bv);
		else if (builder is Date64Array.Builder d64 && value is DateTime dt) d64.Append(dt);
		else if (builder is TimestampArray.Builder ts && value is DateTimeOffset dto) ts.Append(dto);
		else AppendNull(builder);
	}

	private static void AppendNull(IArrowArrayBuilder builder)
	{
		switch (builder)
		{
			case BooleanArray.Builder b: b.AppendNull(); break;
			case Int32Array.Builder b: b.AppendNull(); break;
			case Int64Array.Builder b: b.AppendNull(); break;
			case DoubleArray.Builder b: b.AppendNull(); break;
			case FloatArray.Builder b: b.AppendNull(); break;
			case StringArray.Builder b: b.AppendNull(); break;
			case TimestampArray.Builder b: b.AppendNull(); break;
			case Date64Array.Builder b: b.AppendNull(); break;
			default: if (builder is StringArray.Builder s) s.AppendNull(); break;
		}
	}

	private static IArrowArray BuildArray(IArrowArrayBuilder builder)
	{
		return builder switch
		{
			BooleanArray.Builder b => b.Build(),
			Int32Array.Builder b => b.Build(),
			Int64Array.Builder b => b.Build(),
			DoubleArray.Builder b => b.Build(),
			FloatArray.Builder b => b.Build(),
			StringArray.Builder b => b.Build(),
			TimestampArray.Builder b => b.Build(),
			Date64Array.Builder b => b.Build(),
			_ => throw new NotSupportedException($"Unsupported builder type for BuildArray: {builder.GetType().Name}")
		};
	}
}
