using System.Text.RegularExpressions;
using Bogus;
using DtPipe.Core.Abstractions;
using DtPipe.Core.Models;
using DtPipe.Core.Options;

using Apache.Arrow;
using Apache.Arrow.Types;
using DtPipe.Core.Infrastructure.Arrow;

namespace DtPipe.Transformers.Columnar.Fake;

/// <summary>
/// Transforms data rows by replacing specified columns with fake data generated by Bogus.
/// Supports column references using {COLUMN_NAME} syntax for composing values.
/// </summary>
public sealed partial class FakeDataTransformer : BaseColumnarTransformer, IRequiresOptions<DtPipe.Transformers.Columnar.Fake.FakeOptions>
{
	private List<DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor>? _processors;
	private readonly DtPipe.Transformers.Columnar.Fake.FakerRegistry _fakerRegistry;
	private readonly DtPipe.Transformers.Columnar.Fake.FakeMappingParser _mappingParser;
	private readonly DtPipe.Transformers.Columnar.Fake.FakeOptions _options;
	private readonly string _locale;
	private readonly Faker _faker;

	// Deterministic mode fields
	private readonly string? _seedColumn;
	private readonly bool _deterministic;
	private readonly bool _skipNull;
	private int _seedColumnIndex = -1;
	private long _rowCounter = 0;

	// Paged caches for deterministic mode
	private Dictionary<int, DtPipe.Transformers.Columnar.Fake.PagedFakeValueCache>? _pagedCaches;

	// State initialized in InitializeAsync
	private int[]? _generationOrder;
	private Dictionary<string, int>? _columnNameToIndex;
	private readonly List<string> _virtualColumns = [];
	private int _realColumnCount;
	private Schema? _outputSchema;

	// Regex for template substitution
	[GeneratedRegex(@"\{([^{}]+)\}", RegexOptions.Compiled)]
	private static partial Regex TemplatePattern();

	public override bool CanProcessColumnar => true;

	public FakeDataTransformer(DtPipe.Transformers.Columnar.Fake.FakeOptions options)
	{
		_options = options;
		_fakerRegistry = new DtPipe.Transformers.Columnar.Fake.FakerRegistry();
		_mappingParser = new DtPipe.Transformers.Columnar.Fake.FakeMappingParser(_fakerRegistry);
		_locale = options.Locale;
		_seedColumn = options.SeedColumn;
		_deterministic = options.Deterministic;
		_skipNull = options.SkipNull;

		_faker = options.Seed.HasValue
			? new Faker(options.Locale) { Random = new Randomizer(options.Seed.Value) }
			: new Faker(options.Locale);

		if (_deterministic && !string.IsNullOrEmpty(_seedColumn))
		{
			throw new ArgumentException("Options --fake-deterministic and --fake-seedcolumn cannot be used together.");
		}

		_mappingParser.ParseAll(options.Fake);
	}

	public bool HasFake => _mappingParser.HasMappings;
	public DtPipe.Transformers.Columnar.Fake.FakerRegistry Registry => _fakerRegistry;

	public override ValueTask<IReadOnlyList<PipeColumnInfo>> InitializeAsync(IReadOnlyList<PipeColumnInfo> columns, CancellationToken ct = default)
	{
		if (!HasFake)
		{
			_processors = null;
			_generationOrder = null;
			return new ValueTask<IReadOnlyList<PipeColumnInfo>>(columns);
		}

		// Build column name to index map
		_columnNameToIndex = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
		_realColumnCount = columns.Count;
		for (var i = 0; i < columns.Count; i++)
		{
			_columnNameToIndex[columns[i].Name] = i;
		}

		// Detect virtual columns
		_virtualColumns.Clear();
		foreach (var colName in _mappingParser.Mappings.Keys)
		{
			if (!_columnNameToIndex.ContainsKey(colName))
			{
				var virtualIndex = _realColumnCount + _virtualColumns.Count;
				_columnNameToIndex[colName] = virtualIndex;
				_virtualColumns.Add(colName);
			}
		}

		var totalColumns = _realColumnCount + _virtualColumns.Count;

		// Build processors
		var processors = new DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor[totalColumns];
		var templateColumns = new List<int>();
		var nonTemplateColumns = new List<int>();

		// Process real columns
		for (var i = 0; i < columns.Count; i++)
		{
			var colName = columns[i].Name;
			if (!_mappingParser.Mappings.TryGetValue(colName, out var value))
			{
				continue;
			}

			if (DtPipe.Transformers.Columnar.Fake.FakeMappingParser.IsTemplate(value))
			{
				var refCols = DtPipe.Transformers.Columnar.Fake.FakeMappingParser.ExtractReferencedColumns(value);
				processors[i] = new DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor(i, value, refCols);
				templateColumns.Add(i);
			}
			else
			{
				var generator = BuildGenerator(value, colName);
				processors[i] = new DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor(i, generator, value);
				nonTemplateColumns.Add(i);
			}
		}

		// Process virtual columns
		foreach (var virtualCol in _virtualColumns)
		{
			var virtualIndex = _columnNameToIndex[virtualCol];
			var value = _mappingParser.Mappings[virtualCol];

			if (DtPipe.Transformers.Columnar.Fake.FakeMappingParser.IsTemplate(value))
			{
				var refCols = DtPipe.Transformers.Columnar.Fake.FakeMappingParser.ExtractReferencedColumns(value);
				processors[virtualIndex] = new DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor(virtualIndex, value, refCols);
				templateColumns.Add(virtualIndex);
			}
			else
			{
				var generator = BuildGenerator(value, virtualCol);
				processors[virtualIndex] = new DtPipe.Transformers.Columnar.Fake.FakeColumnProcessor(virtualIndex, generator, value);
				nonTemplateColumns.Add(virtualIndex);
			}
		}

		_processors = processors.ToList();
		_generationOrder = [.. nonTemplateColumns, .. templateColumns];

		// Resolve seed column index
		if (_seedColumn is not null && !_columnNameToIndex.TryGetValue(_seedColumn, out _seedColumnIndex))
		{
			throw new InvalidOperationException($"Seed column '{_seedColumn}' not found in result set.");
		}

		// Initialize deterministic caches
		if (_deterministic || _seedColumnIndex >= 0)
		{
			_pagedCaches = [];
			foreach (var idx in _generationOrder)
			{
				var proc = _processors[idx];
				if (proc.Generator is not null)
				{
					_pagedCaches[idx] = new DtPipe.Transformers.Columnar.Fake.PagedFakeValueCache(_locale, proc.Generator, proc.FakerHash);
				}
			}
		}

		// Prepare output columns schema
		var outputColumns = new List<PipeColumnInfo>(columns);
		foreach (var virtualColName in _virtualColumns)
		{
			var fakerPath = _mappingParser.Mappings[virtualColName];
			Type colType = typeof(string);

			// Try to infer type from registry
			if (!DtPipe.Transformers.Columnar.Fake.FakeMappingParser.IsTemplate(fakerPath))
			{
				var hashIndex = fakerPath.IndexOf('#');
				var basePath = hashIndex >= 0 ? fakerPath[..hashIndex] : fakerPath;
				colType = _fakerRegistry.GetReturnType(basePath) ?? typeof(string);
			}

			outputColumns.Add(new PipeColumnInfo(virtualColName, colType, true));
		}

		_outputSchema = BuildArrowSchema(outputColumns);
		return new ValueTask<IReadOnlyList<PipeColumnInfo>>(outputColumns);
	}

	private Schema BuildArrowSchema(IReadOnlyList<PipeColumnInfo> columns)
	{
		var builder = new Schema.Builder();
		foreach (var col in columns)
		{
			builder.Field(new Field(col.Name, ArrowTypeMapper.GetArrowType(col.ClrType), true));
		}
		return builder.Build();
	}

	private Func<Faker, object?> BuildGenerator(string fakerPath, string colName)
	{
		var hashIndex = fakerPath.IndexOf('#');
		var basePath = hashIndex >= 0 ? fakerPath[..hashIndex] : fakerPath;

		var generator = _fakerRegistry.GetGenerator(basePath);
		if (generator is not null) return generator;

		// If the dataset prefix is a known Bogus dataset (e.g. "name", "address") but the full path
		// wasn't found, it's a genuine configuration error (typo in method name).
		// Otherwise, treat as a hardcoded literal string.
		var dotIndex = basePath.IndexOf('.');
		if (dotIndex > 0)
		{
			var datasetName = basePath[..dotIndex];
			if (_fakerRegistry.HasDataset(datasetName))
			{
				throw new ArgumentException($"Unknown fake provider: '{basePath}' for column '{colName}'. " +
					$"Dataset '{datasetName}' exists but method '{basePath[(dotIndex + 1)..]}' was not found.");
			}
		}

		// Fallback: treat as hardcoded literal string
		return _ => fakerPath;
	}

	public override object?[]? Transform(object?[] row)
	{
		_rowCounter++;

		if (_processors is null || _generationOrder is null) return row;

		var totalColumns = _realColumnCount + _virtualColumns.Count;
		var resultRow = new object?[totalColumns];
		System.Array.Copy(row, resultRow, _realColumnCount);

		// Initialize virtual columns with null for safety
		for (int i = 0; i < _virtualColumns.Count; i++)
		{
			resultRow[_realColumnCount + i] = null;
		}

		// Row-level seed for deterministic mode
		int? rowSeed = null;
		if (_deterministic)
		{
			rowSeed = (int)(_rowCounter & 0x7FFFFFFF);
		}
		else if (_seedColumnIndex >= 0)
		{
			var seedVal = resultRow[_seedColumnIndex];
			if (seedVal is not null)
			{
				rowSeed = (int)(DtPipe.Transformers.Columnar.Fake.StableHash.Compute(seedVal) & 0x7FFFFFFF);
			}
		}

		foreach (var idx in _generationOrder)
		{
			// Skip if source is null and SkipNull is enabled (for real columns only)
			if (_skipNull && idx < _realColumnCount && resultRow[idx] is null)
			{
				continue;
			}

			var proc = _processors[idx];
			if (proc.IsTemplate)
			{
				resultRow[idx] = ProcessTemplate(resultRow, proc.Template!, proc.ReferencedColumns!);
			}
			else if (proc.Generator is not null)
			{
				if (rowSeed.HasValue && _pagedCaches!.TryGetValue(idx, out var cache))
				{
					// Use paged cache for deterministic/seedcolumn mode
					resultRow[idx] = cache.GetValue(rowSeed.Value);
				}
				else
				{
					// Normal random mode
					resultRow[idx] = proc.Generator(_faker);
				}
			}
		}

		return resultRow;
	}

	private object? ProcessTemplate(object?[] row, string template, HashSet<string> refCols)
	{
		return TemplatePattern().Replace(template, match =>
		{
			var colName = match.Groups[1].Value;
			if (_columnNameToIndex!.TryGetValue(colName, out var idx))
			{
				return row[idx]?.ToString() ?? "";
			}
			return match.Value;
		});
	}

	protected override ValueTask<RecordBatch?> TransformBatchSafeAsync(RecordBatch batch, CancellationToken ct = default)
	{
		if (_processors is null || _generationOrder is null || _outputSchema is null)
			return new ValueTask<RecordBatch?>(batch);

		int rowCount = batch.Length;
		int totalColumns = _processors.Count;
		var builders = CreateBuilders(_outputSchema, rowCount);

		// Row buffer for Bogus and Templates
		var rowBuffer = new object?[totalColumns];

		// Appenders for efficient batching (reusing bridge logic or similar)
		// To simplify, we'll use a direct loop.

		for (int i = 0; i < rowCount; i++)
		{
			_rowCounter++;

			// 1. Extract real columns from incoming batch into rowBuffer
			for (int colIdx = 0; colIdx < _realColumnCount; colIdx++)
			{
				rowBuffer[colIdx] = ArrowTypeMapper.GetValue(batch.Column(colIdx), i);
			}
			// Initialize virtual columns if any
			for (int colIdx = _realColumnCount; colIdx < totalColumns; colIdx++)
			{
				rowBuffer[colIdx] = null;
			}

			// 2. Deterministic Row Seed
			int? rowSeed = null;
			if (_deterministic)
			{
				rowSeed = (int)(_rowCounter & 0x7FFFFFFF);
			}
			else if (_seedColumnIndex >= 0)
			{
				var seedVal = rowBuffer[_seedColumnIndex];
				if (seedVal is not null)
				{
					rowSeed = (int)(DtPipe.Transformers.Columnar.Fake.StableHash.Compute(seedVal) & 0x7FFFFFFF);
				}
			}

			// 3. Process Generation Order
			foreach (var idx in _generationOrder)
			{
				if (_skipNull && idx < _realColumnCount && rowBuffer[idx] is null)
				{
					continue;
				}

				var proc = _processors[idx];
				if (proc.IsTemplate)
				{
					rowBuffer[idx] = ProcessTemplate(rowBuffer, proc.Template!, proc.ReferencedColumns!);
				}
				else if (proc.Generator is not null)
				{
					if (rowSeed.HasValue && _pagedCaches!.TryGetValue(idx, out var cache))
					{
						rowBuffer[idx] = cache.GetValue(rowSeed.Value);
					}
					else
					{
						rowBuffer[idx] = proc.Generator(_faker);
					}
				}
			}

			// 4. Append row to builders
			for (int colIdx = 0; colIdx < totalColumns; colIdx++)
			{
				ArrowTypeMapper.AppendValue(builders[colIdx], rowBuffer[colIdx]);
			}
		}

		// 5. Build final result batch
		var resultArrays = builders.Select(b => ArrowTypeMapper.BuildArray(b)).ToList();
		return new ValueTask<RecordBatch?>(new RecordBatch(_outputSchema, resultArrays, rowCount));
	}

	private static IArrowArrayBuilder[] CreateBuilders(Schema schema, int capacity)
	{
		return schema.FieldsList.Select(f => ArrowTypeMapper.CreateBuilder(f.DataType)).ToArray();
	}
}
