using Bogus;
using QueryDump.Core;
using QueryDump.Core.Options;

namespace QueryDump.Transformers.Fake;

/// <summary>
/// Transforms data rows by replacing specified columns with fake data generated by Bogus.
/// </summary>
public sealed class FakeDataTransformer : IDataTransformer, IRequiresOptions<FakeOptions>
{
    private readonly Dictionary<string, string> _mappings = new(StringComparer.OrdinalIgnoreCase);
    private readonly FakerRegistry _registry;
    private readonly Faker _faker;
    
    // State initialized in InitializeAsync
    private (int Index, Func<Faker, object?> Generator)?[]? _columnGenerators;

    public FakeDataTransformer(FakeOptions options)
    {
        _registry = new FakerRegistry();
        _faker = options.Seed.HasValue 
            ? new Faker(options.Locale) { Random = new Randomizer(options.Seed.Value) } 
            : new Faker(options.Locale);

        if (options.Mappings is not null)
        {
            foreach (var mapping in options.Mappings)
            {
                ParseMapping(mapping);
            }
        }
    }

    /// <summary>
    /// Indicates whether any column mappings are configured.
    /// </summary>
    public bool HasMappings => _mappings.Count > 0;

    /// <summary>
    /// Get the FakerRegistry for listing available fakers.
    /// </summary>
    public FakerRegistry Registry => _registry;

    public ValueTask InitializeAsync(IReadOnlyList<ColumnInfo> columns, CancellationToken ct = default)
    {
        if (!HasMappings)
        {
            _columnGenerators = null;
            return ValueTask.CompletedTask;
        }

        _columnGenerators = new (int Index, Func<Faker, object?> Generator)?[columns.Count];

        for (var i = 0; i < columns.Count; i++)
        {
            var colName = columns[i].Name;
            if (_mappings.TryGetValue(colName, out var fakerPath))
            {
                var generator = _registry.GetGenerator(fakerPath);
                if (generator is not null)
                {
                    _columnGenerators[i] = (i, generator);
                }
                else
                {
                    Console.Error.WriteLine($"Warning: Unknown faker '{fakerPath}' for column '{colName}'");
                }
            }
        }

        return ValueTask.CompletedTask;
    }

    public ValueTask<IReadOnlyList<object?[]>> TransformAsync(IReadOnlyList<object?[]> rows, CancellationToken ct = default)
    {
        if (_columnGenerators is null || rows.Count == 0)
        {
             return new ValueTask<IReadOnlyList<object?[]>>(rows);
        }

        var result = new List<object?[]>(rows.Count);
        foreach (var row in rows)
        {
            var newRow = new object?[row.Length];
            Array.Copy(row, newRow, row.Length);

            foreach (var gen in _columnGenerators)
            {
                if (gen.HasValue)
                {
                    newRow[gen.Value.Index] = gen.Value.Generator(_faker);
                }
            }

            result.Add(newRow);
        }

        return new ValueTask<IReadOnlyList<object?[]>>(result);
    }

    private void ParseMapping(string mapping)
    {
        // Format: COLUMN:dataset.method (e.g., "VILLE:address.city")
        var separatorIndex = mapping.IndexOf(':');
        if (separatorIndex <= 0 || separatorIndex >= mapping.Length - 1)
        {
            Console.Error.WriteLine($"Warning: Invalid mapping format '{mapping}'. Expected 'COLUMN:dataset.method'");
            return;
        }

        var column = mapping[..separatorIndex].Trim();
        var fakerPath = mapping[(separatorIndex + 1)..].Trim().ToLowerInvariant();

        if (string.IsNullOrEmpty(column) || string.IsNullOrEmpty(fakerPath))
        {
            Console.Error.WriteLine($"Warning: Invalid mapping '{mapping}'. Column and faker path cannot be empty.");
            return;
        }

        if (!_registry.HasGenerator(fakerPath))
        {
            Console.Error.WriteLine($"Warning: Unknown faker '{fakerPath}'. Use --fake-list to see available options.");
        }

        _mappings[column] = fakerPath;
    }
}
