#!/bin/bash

# Configuration
SCRIPT_DIR="$(dirname "$0")"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
DIST_DIR="$PROJECT_ROOT/dist/release"
DTPIPE_BIN="$DIST_DIR/dtpipe"
ARTIFACTS_DIR="tests/scripts/artifacts"
mkdir -p "$ARTIFACTS_DIR"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if dtpipe exists
if [ ! -f "$DTPIPE_BIN" ]; then
    echo -e "${RED}Error: dtpipe binary not found at $DTPIPE_BIN${NC}"
    echo "Please run ./build.sh first."
    exit 1
fi

# Function to check Docker availability
check_docker() {
    if ! command -v docker &> /dev/null; then
        echo -e "${YELLOW}Docker is not installed. Skipping container tests.${NC}"
        return 1
    fi

    if ! docker info &> /dev/null; then
        echo -e "${YELLOW}Docker is installed but not running (or permission denied). Skipping container tests.${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Docker is available.${NC}"
    return 0
}

# Run Docker Check
if ! check_docker; then
    echo -e "${YELLOW}SKIP: Docker-based integration tests skipped.${NC}"
    exit 0
fi

echo -e "${GREEN}Starting Docker-based Integration Tests...${NC}"

# Start shared infrastructure
INFRA_DIR="$PROJECT_ROOT/tests/infra"
if [ -f "$INFRA_DIR/start_infra.sh" ]; then
    echo "Starting shared infrastructure..."
    "$INFRA_DIR/start_infra.sh"
else
    echo -e "${RED}Error: start_infra.sh not found at $INFRA_DIR${NC}"
    exit 1
fi

# Cleanup function - only clean up test artifacts, not containers
cleanup() {
    echo "Cleaning up test artifacts..."
    rm -f "$ARTIFACTS_DIR"/postgres_out.csv "$ARTIFACTS_DIR"/mssql_out.csv "$ARTIFACTS_DIR"/oracle_out.csv
}
trap cleanup EXIT


# --- TEST: Postgres ---
echo "------------------------------------------------"
echo "Starting PostgreSQL Test..."

# Create seed data in the shared container
docker exec -i dtpipe-integ-postgres psql -U postgres -d integration <<EOF
DROP TABLE IF EXISTS users;
CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(50));
INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com'), ('Bob', 'bob@example.com');
EOF

echo "Running export from Postgres..."
$DTPIPE_BIN --input "pg:Host=localhost;Port=5440;Username=postgres;Password=password;Database=integration" \
               --query "SELECT * FROM users ORDER BY id" \
               --output "$ARTIFACTS_DIR/postgres_out.csv"

# Verify Output
if grep -q "Alice" "$ARTIFACTS_DIR/postgres_out.csv" && grep -q "Bob" "$ARTIFACTS_DIR/postgres_out.csv"; then
    echo -e "${GREEN}✓ Postgres Test Passed${NC}"
else
    echo -e "${RED}✗ Postgres Test Failed${NC}"
    cat "$ARTIFACTS_DIR/postgres_out.csv"
    exit 1
fi

# --- TEST: MSSQL ---
echo "------------------------------------------------"
echo "Starting MSSQL Test..."

# Create seed data in the shared container using mssql-tools
docker exec -i dtpipe-integ-mssql-tools /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123!" <<EOF
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Users') DROP TABLE Users;
GO
CREATE TABLE Users (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(50), Email NVARCHAR(50));
INSERT INTO Users (Name, Email) VALUES ('Charlie', 'charlie@example.com'), ('David', 'david@example.com');
GO
EOF



echo "Running export from MSSQL..."
$DTPIPE_BIN --input "mssql:Server=localhost,1434;Database=master;User Id=sa;Password=Password123!;TrustServerCertificate=True" \
               --query "SELECT * FROM Users ORDER BY Id" \
               --output "$ARTIFACTS_DIR/mssql_out.csv"

# Verify Output
if grep -q "Charlie" "$ARTIFACTS_DIR/mssql_out.csv" && grep -q "David" "$ARTIFACTS_DIR/mssql_out.csv"; then
    echo -e "${GREEN}✓ MSSQL Test Passed${NC}"
else
    echo -e "${RED}✗ MSSQL Test Failed${NC}"
    cat "$ARTIFACTS_DIR/mssql_out.csv"
    exit 1
fi

# --- TEST: Oracle ---
echo "------------------------------------------------"
echo "Starting Oracle Test..."

# Seed data in the shared container
# Note: Using testuser as defined in docker-compose.yml
docker exec -i dtpipe-integ-oracle sqlplus testuser/password@localhost:1521/FREEPDB1 <<EOF
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Users';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE Users (Id NUMBER GENERATED BY DEFAULT AS IDENTITY, Name VARCHAR2(50), Email VARCHAR2(50));
INSERT INTO Users (Name, Email) VALUES ('Eve', 'eve@example.com');
INSERT INTO Users (Name, Email) VALUES ('Frank', 'frank@example.com');
COMMIT;
EXIT;
EOF

echo "Running export from Oracle..."
$DTPIPE_BIN --input "ora:Data Source=localhost:1522/FREEPDB1;User Id=testuser;Password=password;" \
               --query "SELECT * FROM Users ORDER BY Id" \
               --output "$ARTIFACTS_DIR/oracle_out.csv"

# Verify Output
if grep -q "Eve" "$ARTIFACTS_DIR/oracle_out.csv" && grep -q "Frank" "$ARTIFACTS_DIR/oracle_out.csv"; then
    echo -e "${GREEN}✓ Oracle Test Passed${NC}"
else
    echo -e "${RED}✗ Oracle Test Failed${NC}"
    cat "$ARTIFACTS_DIR/oracle_out.csv"
    exit 1
fi

echo -e "${GREEN}All Docker tests passed!${NC}"
exit 0
