#!/bin/bash

# Configuration
SCRIPT_DIR="$(dirname "$0")"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
DIST_DIR="$PROJECT_ROOT/dist/release"
QUERYDUMP_BIN="$DIST_DIR/querydump"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if querydump exists
if [ ! -f "$QUERYDUMP_BIN" ]; then
    echo -e "${RED}Error: querydump binary not found at $QUERYDUMP_BIN${NC}"
    echo "Please run ./build.sh first."
    exit 1
fi

# Function to check Docker availability
check_docker() {
    if ! command -v docker &> /dev/null; then
        echo -e "${YELLOW}Docker is not installed. Skipping container tests.${NC}"
        return 1
    fi

    if ! docker info &> /dev/null; then
        echo -e "${YELLOW}Docker is installed but not running (or permission denied). Skipping container tests.${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Docker is available.${NC}"
    return 0
}

# Run Docker Check
if ! check_docker; then
    echo -e "${YELLOW}SKIP: Docker-based integration tests skipped.${NC}"
    exit 0
fi

echo -e "${GREEN}Starting Docker-based Integration Tests...${NC}"

# Cleanup function
cleanup() {
    echo "Cleaning up containers..."
    docker rm -f querydump-postgres &> /dev/null
    docker rm -f querydump-mssql &> /dev/null
    docker rm -f querydump-oracle &> /dev/null
}
trap cleanup EXIT

# --- TEST: Postgres ---
echo "------------------------------------------------"
echo "Starting PostgreSQL Test..."

docker run --name querydump-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres:latest
# Wait for PG to be ready
echo "Waiting for Postgres..."
sleep 5

# Create seed data
docker exec -i querydump-postgres psql -U postgres <<EOF
CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(50));
INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com'), ('Bob', 'bob@example.com');
EOF

echo "Running export from Postgres..."
$QUERYDUMP_BIN --input "postgres:Host=localhost;Port=5432;Username=postgres;Password=mysecretpassword;Database=postgres" \
               --query "SELECT * FROM users ORDER BY id" \
               --output "postgres_out.csv"

# Verify Output
if grep -q "Alice" "postgres_out.csv" && grep -q "Bob" "postgres_out.csv"; then
    echo -e "${GREEN}✓ Postgres Test Passed${NC}"
else
    echo -e "${RED}✗ Postgres Test Failed${NC}"
    cat postgres_out.csv
    exit 1
fi
rm postgres_out.csv

# --- TEST: MSSQL ---
echo "------------------------------------------------"
echo "Starting MSSQL Test..."

docker run --name querydump-mssql -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=MySecretPassword123!" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

# Wait for MSSQL (slower startup)
echo "Waiting for MSSQL (15s)..."
sleep 15

# Create seed data (using sqlcmd inside container)
docker exec -i querydump-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "MySecretPassword123!" -C <<EOF
CREATE DATABASE TestDB;
GO
USE TestDB;
CREATE TABLE Users (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(50), Email NVARCHAR(50));
INSERT INTO Users (Name, Email) VALUES ('Charlie', 'charlie@example.com'), ('David', 'david@example.com');
GO
EOF

echo "Running export from MSSQL..."
$QUERYDUMP_BIN --input "mssql:Server=localhost,1433;Database=TestDB;User Id=sa;Password=MySecretPassword123!;TrustServerCertificate=True" \
               --query "SELECT * FROM Users ORDER BY Id" \
               --output "mssql_out.csv"

# Verify Output
if grep -q "Charlie" "mssql_out.csv" && grep -q "David" "mssql_out.csv"; then
    echo -e "${GREEN}✓ MSSQL Test Passed${NC}"
else
    echo -e "${RED}✗ MSSQL Test Failed${NC}"
    cat mssql_out.csv
    exit 1
fi
rm mssql_out.csv

# --- TEST: Oracle ---
echo "------------------------------------------------"
echo "Starting Oracle Test..."

# Use slim image for speed
docker run --name querydump-oracle -e ORACLE_PASSWORD=MySecretPassword123! -p 1521:1521 -d gvenzl/oracle-free:slim

# Wait for Oracle (slowest)
echo "Waiting for Oracle (30s)..."
sleep 30

# Seed data
# Note: Oracle system user, typical SID=FREE or service=FREEPDB1
docker exec -i querydump-oracle sqlplus system/MySecretPassword123!@localhost:1521/FREEPDB1 <<EOF
CREATE TABLE Users (Id NUMBER GENERATED BY DEFAULT AS IDENTITY, Name VARCHAR2(50), Email VARCHAR2(50));
INSERT INTO Users (Name, Email) VALUES ('Eve', 'eve@example.com');
INSERT INTO Users (Name, Email) VALUES ('Frank', 'frank@example.com');
COMMIT;
EXIT;
EOF

echo "Running export from Oracle..."
$QUERYDUMP_BIN --input "oracle:Data Source=localhost:1521/FREEPDB1;User Id=system;Password=MySecretPassword123!;" \
               --query "SELECT * FROM Users ORDER BY Id" \
               --output "oracle_out.csv"

# Verify Output
if grep -q "Eve" "oracle_out.csv" && grep -q "Frank" "oracle_out.csv"; then
    echo -e "${GREEN}✓ Oracle Test Passed${NC}"
else
    echo -e "${RED}✗ Oracle Test Failed${NC}"
    cat oracle_out.csv
    exit 1
fi
rm oracle_out.csv

echo -e "${GREEN}All Docker tests passed!${NC}"
exit 0
